<?php
require_once __DIR__ . '/security.php';
require_once __DIR__ . '/db.php';

function gb_session_start(): void {
  if (session_status() === PHP_SESSION_ACTIVE) return;

  ini_set('session.use_strict_mode', '1');
  ini_set('session.use_only_cookies', '1');

  // Cookie settings (best effort across hosts)
  $params = session_get_cookie_params();
  $opts = [
    'lifetime' => 0,
    'path' => $params['path'] ?? '/','domain' => $params['domain'] ?? '',
    'secure' => gb_is_https(),
    'httponly' => true,
    'samesite' => 'Strict',
  ];
  if (PHP_VERSION_ID >= 70300) {
    session_set_cookie_params($opts);
  } else {
    // Fallback for very old PHP (should be rare on modern hosts)
    ini_set('session.cookie_secure', $opts['secure'] ? '1' : '0');
    ini_set('session.cookie_httponly', '1');
  }

  session_name('GBSESSID');
  session_start();
}

function gb_auth_row(string $dataDir): array {
  if (!gb_db_exists($dataDir)) return [];
  try {
    $pdo = gb_pdo($dataDir);
    $r = $pdo->query('SELECT * FROM gb_auth WHERE id=1')->fetch();
    return is_array($r) ? $r : [];
  } catch (Throwable $e) {
    return [];
  }
}

function gb_auth_locked_until(array $row): int {
  $lu = (string)($row['locked_until'] ?? '');
  if ($lu === '') return 0;
  $t = strtotime($lu);
  return $t === false ? 0 : $t;
}

function gb_auth_is_configured(string $dataDir): bool {
  $row = gb_auth_row($dataDir);
  return !empty($row['password_hash']) || !empty($row['pin_hash']);
}

function gb_verify(string $dataDir, string $attempt): bool {
  $attempt = trim($attempt);
  if ($attempt === '') return false;
  $row = gb_auth_row($dataDir);
  if (!$row) return false;

  $lockedUntil = gb_auth_locked_until($row);
  if ($lockedUntil > time()) return false;

  $ok = false;
  if (!empty($row['password_hash']) && password_verify($attempt, (string)$row['password_hash'])) $ok = true;
  if (!$ok && !empty($row['pin_hash']) && password_verify($attempt, (string)$row['pin_hash'])) $ok = true;

  // Update lockout counters (best effort)
  try {
    $pdo = gb_pdo($dataDir);
    if ($ok) {
      $pdo->exec('UPDATE gb_auth SET failed_attempts=0, locked_until=NULL WHERE id=1');
    } else {
      $pdo->exec('UPDATE gb_auth SET failed_attempts = failed_attempts + 1 WHERE id=1');
      $fa = (int)($pdo->query('SELECT failed_attempts FROM gb_auth WHERE id=1')->fetchColumn() ?: 0);
      if ($fa >= 5) {
        $st = $pdo->prepare('UPDATE gb_auth SET failed_attempts=0, locked_until=:lu WHERE id=1');
        $st->execute([':lu' => date('Y-m-d H:i:s', time() + 300)]); // 5 minutes
      }
    }
  } catch (Throwable $e) {
    // ignore
  }

  return $ok;
}

function gb_is_authed(string $dataDir): bool {
  gb_session_start();
  $until = (int)($_SESSION['gb_authed_until'] ?? 0);
  return $until > time();
}

function gb_try_login(string $dataDir, int $minutes = 10): bool {
  gb_session_start();
  if (gb_is_authed($dataDir)) return true;
  if ($_SERVER['REQUEST_METHOD'] !== 'POST') return false;

  // CSRF for the unlock form (generated by gb_require_auth)
  $sent = (string)($_POST['gb_unlock_csrf'] ?? '');
  $stored = (string)($_SESSION['gb_unlock_csrf'] ?? '');
  if ($stored !== '' && !hash_equals($stored, $sent)) {
    return false;
  }

  $attempt = (string)($_POST['gb_login_attempt'] ?? '');
  if ($attempt === '') return false;

  if (gb_verify($dataDir, $attempt)) {
    session_regenerate_id(true);
    $_SESSION['gb_authed_until'] = time() + ($minutes * 60);
    return true;
  }
  return false;
}

function gb_require_auth(string $dataDir, int $minutes = 10, string $error = ''): void {
  // If the app isn't configured, avoid a confusing password prompt.
  if (!gb_db_exists($dataDir)) {
    http_response_code(503);
    echo '<!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">';
    echo '<link rel="stylesheet" href="css/style.css"><title>Not configured</title></head><body class="auth-body"><div class="app auth">';
    echo '<div class="section"><h2>Not configured</h2><div class="small">Database not initialized. Open <code>setup.php</code>.</div>';
    echo '<div class="buttons"><a class="btn primary" href="setup.php">Open setup</a></div></div></div></body></html>';
    exit;
  }

  // If the unlock POST succeeds, redirect to the same URL as a GET.
  // This prevents accidental processing of the unlock POST as an app action
  // (which would fail CSRF and confuse the user).
  if (gb_try_login($dataDir, $minutes)) {
    // Always redirect after an unlock POST. This avoids continuing to process the POST
    // as an application action (which could fail CSRF or double-submit).
    if ($_SERVER['REQUEST_METHOD'] === 'POST') {
      $dest = $_SERVER['REQUEST_URI'] ?? 'index.php';
      header('Location: '.$dest, true, 303);
      exit;
    }
    return;
  }

  $row = gb_auth_row($dataDir);
  $lockedUntil = gb_auth_locked_until($row);
  $lockedMsg = '';
  if ($lockedUntil > time()) {
    $lockedMsg = 'Too many failed attempts. Try again after '.date('g:i a', $lockedUntil).'.';
  }

  echo '<!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">';
  echo '<link rel="stylesheet" href="css/style.css"><title>Unlock</title></head><body class="auth-body"><div class="app auth">';
  echo '<div class="section"><h2>Unlock Admin</h2><div class="small">Enter your admin password or PIN to unlock for '.$minutes.' minutes.</div>';
  if ($error !== '') echo '<div class="badge warn" style="margin-top:10px;">'.htmlspecialchars($error, ENT_QUOTES, 'UTF-8').'</div>';
  if ($lockedMsg !== '') echo '<div class="badge warn" style="margin-top:10px;">'.htmlspecialchars($lockedMsg, ENT_QUOTES, 'UTF-8').'</div>';
  echo '<form method="post" style="margin-top:12px;">';
  // Per-form CSRF token (avoids circular deps)
  $tok = bin2hex(random_bytes(32));
  gb_session_start();
  $_SESSION['gb_unlock_csrf'] = $tok;
  echo '<input type="hidden" name="gb_unlock_csrf" value="'.htmlspecialchars($tok, ENT_QUOTES, 'UTF-8').'">';
  echo '<input type="password" name="gb_login_attempt" placeholder="Password or PIN" autocomplete="current-password" inputmode="numeric">';
  echo '<div class="buttons"><button class="primary" type="submit">Unlock</button></div>';
  echo '</form></div></div></body></html>';
  exit;
}

function gb_logout(): void {
  gb_session_start();
  $_SESSION = [];
  if (ini_get('session.use_cookies')) {
    $p = session_get_cookie_params();
    setcookie(session_name(), '', time()-42000, $p['path'] ?? '/', $p['domain'] ?? '', gb_is_https(), true);
  }
  session_destroy();
}
